import type { TournamentMutationInput } from "./types";

export const seedTournaments: TournamentMutationInput[] = [
  {
    slug: "neon-clash-open",
    name: "Neon Clash Open",
    game: "Valorant",
    summary: "Open-registration campus Valorant bracket with live casting and team check-in.",
    formLink: "/tournament-hub#register-neon-clash-open",
    detailLink: "/tournament-hub#details-neon-clash-open",
    dateUploaded: "2026-06-03T09:00:00Z",
    eventDate: "2026-06-14T13:00:00Z",
    registrationClosesAt: "2026-06-12T18:00:00Z",
    format: "5v5, double elimination",
    status: "Registration live",
    slots: "24/32 teams filled",
    location: "Elevation Arena Alpha",
    archived: false,
  },
  {
    slug: "battleground-blitz-cup",
    name: "Battleground Blitz Cup",
    game: "BGMI",
    summary: "Squad-based BGMI event with qualifier lobbies feeding into a final points race.",
    formLink: "/tournament-hub#register-battleground-blitz-cup",
    detailLink: "/tournament-hub#details-battleground-blitz-cup",
    dateUploaded: "2026-06-02T10:00:00Z",
    eventDate: "2026-06-18T11:00:00Z",
    registrationClosesAt: "2026-06-14T18:00:00Z",
    format: "Squads, 6-match finals",
    status: "Roster lock in 4 days",
    slots: "18/20 squads filled",
    location: "Mobile Stage Nexus",
    archived: false,
  },
  {
    slug: "rocket-rumble-night",
    name: "Rocket Rumble Night",
    game: "Rocket League",
    summary: "Fast-paced evening bracket for club teams and invited campus challengers.",
    formLink: "/tournament-hub#register-rocket-rumble-night",
    detailLink: "/tournament-hub#details-rocket-rumble-night",
    dateUploaded: "2026-06-01T08:30:00Z",
    eventDate: "2026-06-21T16:00:00Z",
    registrationClosesAt: "2026-06-20T12:00:00Z",
    format: "3v3 Swiss into playoffs",
    status: "Check-in opens soon",
    slots: "12/16 teams filled",
    location: "Skybox Arena",
    archived: false,
  },
  {
    slug: "cyber-checkmate-series",
    name: "Cyber Checkmate Series",
    game: "Chess",
    summary: "Rapid Swiss series with standings, tiebreaks, and MVP board updates.",
    formLink: "/tournament-hub#archive-cyber-checkmate-series",
    detailLink: "/tournament-hub#results-cyber-checkmate-series",
    dateUploaded: "2026-05-28T14:30:00Z",
    eventDate: "2026-05-30T09:00:00Z",
    registrationClosesAt: null,
    format: "Rapid Swiss, 7 rounds",
    status: "Results published",
    slots: "Winner: Arjun S.",
    location: "Strategy Lab",
    archived: true,
  },
  {
    slug: "free-fire-flashpoint",
    name: "Free Fire Flashpoint",
    game: "Free Fire",
    summary: "Archived squad tournament with VOD, standings, and finals recap links.",
    formLink: "/tournament-hub#archive-free-fire-flashpoint",
    detailLink: "/tournament-hub#results-free-fire-flashpoint",
    dateUploaded: "2026-05-24T13:00:00Z",
    eventDate: "2026-05-27T18:00:00Z",
    registrationClosesAt: null,
    format: "Squads, points race",
    status: "VOD and standings live",
    slots: "Winner: Team Ember",
    location: "Mobile Stage Nexus",
    archived: true,
  },
  {
    slug: "campus-counter-strike-finals",
    name: "Campus Counter-Strike Finals",
    game: "CS2",
    summary: "Final campus CS2 playoff bracket with highlight package and match stats.",
    formLink: "/tournament-hub#archive-campus-counter-strike-finals",
    detailLink: "/tournament-hub#results-campus-counter-strike-finals",
    dateUploaded: "2026-05-18T15:00:00Z",
    eventDate: "2026-05-22T17:00:00Z",
    registrationClosesAt: null,
    format: "5v5, BO3 playoffs",
    status: "Highlights uploaded",
    slots: "Winner: Headshot Unit",
    location: "Elevation Arena Alpha",
    archived: true,
  },
];
